### ISSUE TITLE
Confusion about dependencies

### ISSUE THREAD

**Issue by dpassen** [armindarvish/consult-gh#104]
consult-gh declares a dependency on `(gh "2.29")`. It appears that is intended to refer to the CLI tool (https://github.com/cli/cli/releases/tag/v2.29.0). My emacs package manager, [elpaca](https://github.com/progfolio/elpaca) seems to interpret that dependency as the emacs library, [gh](https://melpa.org/#/gh) which notably lacks a version corresponding to "2.29" and as such, is not installable.

**Comment by armindarvish** [comment]
@dpassen Yes, you are right. That was left over from some historic reasons. I have resolved that now in both develop and main branch. so update and try again. closing this now.
