### ISSUE TITLE
Browsing code of specific user

### ISSUE THREAD

**Issue by AdrienWehrle** [armindarvish/consult-gh#145]
Hi!

thank you a lot for working on this very useful tool! :) 

I'd like to use `consult-gh-search-code` to browse my own code database only. I could do so by passing `#test -- --owner=AdrienWehrle` but typing this every single time is rather inefficient. Would you see a way around this like setting some customized default command lines arguments where I could set owner continuously?

Thank you a lot in advance for your help! :)

**Comment by armindarvish** [comment]
@AdrienWehrle You can define a new function and append `consult-gh-search-code-args` like this:

```emacs-lisp
(defun consult-gh-search-my-code (&optional initial repo noaction)
  "Search my own code"
  (interactive)
  (let ((consult-gh-search-code-args (append consult-gh-search-code-args '("--owner=AdrienWehrle"))))
    (consult-gh-search-code initial repo noaction)))
```

If that's the only use-case you have for searching code, you can also customize `consult-gh-search-code-args` and add `"--owner=AdrienWehrle"` to that list permanently!

**Comment by AdrienWehrle** [comment]
Amazing thanks a lot! :)
