### ISSUE TITLE
Provide better flow when you do not entirely remember the repository name

### ISSUE THREAD

**Issue by lhernanz** [armindarvish/consult-gh#175]
Thanks for this amazing package!

I am trying to include this package into my workflow and I am facing one challenge. Sometimes I need to use repositories that have long names that are a chore to type (or to remember in some cases). When I want to list the elements of such repos, the only way that I have found is to use the search (or favorite) functionality to find the repo name and the embark integration to list issues, prs, etc. That works fine (although I have found some challenges with embark as described in #174), but I wonder if it would be possible to have a different flow where you use the command that retrieves the objects that you are interested in (e.g. `consult-gh-issue-list`) and it would offer the possibility of completing first the repo name  in case that you do not remember it and, after, it would show the issues/prs/whatever you are looking for. 

Is this flow possible today in some ways that I am missing? If not, is this something that you would entertain implementing in the future?

Thanks

**Comment by armindarvish** [comment]
@lhernanz Yes, there is a better way of achiving what you want and that is using the `C-u` prefix with the interactive commands like `consult-gh-issue-list`, `consult-gh-pr-list`, etc.  

If you regularly do this, you can also define a wrapper around those function like this:  

```emacs-lisp
(defun consult-gh-issue-list-with-search (&optional initial noaction prompt)
(interactive "P")
(let ((current-prefix-arg t))
  (consult-gh-issue-list initial noaction prompt)))
```

\#+beg<el

**Comment by lhernanz** [comment]
@armindarvish thanks for the quick feedback! After updating to latest, this works well. 

Would you be willing to accept a PR to make this behavior customizable? Meaning, that you could change the default so that it always makes a search and you can use the prefix not to do it. Thanks!
