### ISSUE TITLE
Support Multiple Profiles

### ISSUE THREAD

**Issue by armindarvish** [armindarvish/consult-gh#22]
We can possibly support multiple proviles using the environment variable for gh config dir. I need to come up with ideas on how to set it up!

**Comment by armindarvish** [comment]
#+options: toc: nil
This is a test comment from forge!

**Comment by armindarvish** [comment]
#+options: toc: nil
whoami?

**Comment by armindarvish** [comment]
#+options: toc: nil

who is writing this?

**Comment by armindarvish** [comment]
#+options: toc: nil
how about now?

**Comment by ardar848** [comment]
#+options: toc: nil
who is this?

**Comment by armindarvish** [comment]
#+options: toc: nil
#+options: toc: nil
how about now? who is this?

**Comment by ardar848** [comment]
this is another test

**Comment by ardar848** [comment]
#+options: toc: nil
another post from forge

**Comment by ardar848** [comment]
#+options: toc: nil
 new post after switching accounts

**Comment by ardar848** [comment]
#+options: toc: nil
another test

**Comment by ardar848** [comment]
this is a comment from secondary account

**Comment by ardar848** [comment]
comment from other account

**Comment by ardar848** [comment]
This is a test from my secondary account to see if switching accounts is working

**Comment by armindarvish** [comment]
In the latest commits I added `consult-gh-auth-switch` and have added support for magit/forge with switching accounts as well. I am closing this issues now.
