### ISSUE TITLE
void variable consult-preview-key

### ISSUE THREAD

**Issue by guibor** [armindarvish/consult-gh#40]
**Describe the bug**
Debugger entered--Lisp error: (void-variable consult-preview-key)
  #f(compiled-function () #<bytecode 0x1980f3d5d6b54>)()
  funcall(#f(compiled-function () #<bytecode 0x1980f3d5d6b54>))
  eval((funcall #'#f(compiled-function () #<bytecode 0x1980f3d5d6b54>)))
  custom-initialize-reset(consult-gh-preview-key (funcall #'#f(compiled-function () #<bytecode 0x1980f3d5d6b54>)))
  custom-declare-variable(consult-gh-preview-key (funcall #'#f(compiled-function () #<bytecode 0x1980f3d5d6b54>)) "Preview key for consult-gh. This is similar `consu..." :type (choice (const :tag "Any key" any) (list :tag "Debounced" (const :debounce) (float :tag "Seconds" 0.1) (const any)) (const :tag "No preview" nil) (key :tag "Key") (repeat :tag "List of keys" key)))
  byte-code("\300\301!\210\302\303\304\305\306\307\306\310\306\311\306\312\313\314&\15\210\315\316\317\320\321DD\322\306\303\323\324&\7\210\315\325\317\320\326DD\327\306\303\323\324&\7..." [require crm custom-declare-group consult-gh nil "Consulting GitHub CLI" :group convenience minibuffer consult magit :prefix "consult-gh-" custom-declare-variable consult-gh-tempdir funcall function #f(compiled-function () #<bytecode -0x1f9bca5f63ec874>) "Temporary file directory for the `consult-gh' pack..." :type string consult-gh-crm-separator #f(compiled-function () #<bytecode 0x19800936d2b94>) "Separator for multiple selections with completing-..." consult-gh-repo-maxnum #f(compiled-function () #<bytecode 0x19800016f2454>) "Maximum number of output for showing repos with gh..." integer consult-gh-issue-maxnum #f(compiled-function () #<bytecode 0x19800016f2454>) "Maximum number of output for gh issue list and sea..." consult-gh-issues-state-to-show #f(compiled-function () #<bytecode 0x198000fca9b54>) "The state of issues that will be listed by `consul..." (choice "open" "closed" "all") consult-gh-preview-buffer-mode #f(compiled-function () #<bytecode 0x1980fbd16bcd4>) "Major mode to show README of repositories in previ..." symbol consult-gh-default-orgs-list #f(compiled-function () #<bytecode 0x19800016fe914>) "List of default github orgs. A good choice would b..." list consult-gh-preview-buffer-name #f(compiled-function () #<bytecode 0xf33ecfbcd77d5d3>) "Default name to use for preview buffers showing re..." consult-gh-show-preview #f(compiled-function () #<bytecode 0x19800016fe914>) "This variable determines whether `consult-gh' show..." boolean ...] 14)
  #<subr require>(consult-gh)
  apply(#<subr require> consult-gh)
  require(consult-gh)
  eval-expression((require 'consult-gh) nil nil 127)
  funcall-interactively(eval-expression (require 'consult-gh) nil nil 127)
  command-execute(eval-expression)

**To Reproduce**
(require 'consult-gh) for the first time. Doing it again works

**Expected behavior**
No error

**Screenshots**

**Important Information:**
Emacs  : GNU Emacs 29.0.91 (build 1, aarch64-apple-darwin22.4.0, NS appkit-2299.50 Version 13.3.1 (a) (Build 22E772610a))
 of 2023-05-21
Package: 13.2.0

current state:
==============
**Additional context**

**Comment by armindarvish** [comment]
Do you have consult installed? is it loaded before consult-gh? what version of consult do you have installed?

Can you check if the variable `consult-preview-key` exists and is bound to anything before you load consult-gh?

**Comment by brongulus** [comment]
I was facing the same error, it was because I was calling `consult-gh` before loading `consult`. The OP should ensure that consult is not lazy loaded or that add something like
```lisp
(with-eval-after-load 'consult
  (require 'consult-gh))
```

**Comment by armindarvish** [comment]
I updated the README to emphasize that `consult` has to be loaded before `consult-gh`. I am going to close this issues now.
