### ISSUE TITLE
Embarkify

### ISSUE THREAD

**Issue by agzam** [armindarvish/consult-gh#44]
The package currently allows you to set one specific action for `consult-gh-file-action`, `consult-gh-issue-action`, `consult-gh-repo-action`, and that's great.

However, I just realized that even though I often prefer to open things locally instead of browsing, I do sometimes need to open them in the browser. I think it would be great that when you run `consult-gh-find-file`, you could embark-act on the selected row and open it locally, browse it, etc. 

This opens up possibilities, for example, of opening the GitHub blame page for a given file or navigating to a dialog for comparing files between branches. In the future, when PR features are added, other cool actions can be incorporated.

**Comment by armindarvish** [comment]
@agzam This is already the case! If you use the provided embark keymap example, you have exactly those options. for example opening in the browse is bound to "o", copying links to kill-ring is bound to l+key for different links, ...

Watch this video to see it in action: https://www.youtube.com/watch?v=nI00g6IdMyg

**Comment by agzam** [comment]
Ah, I see there are embark action maps, very nice. 

consult-gh-embark-orgs-actions-map
consult-gh-embark-files-actions-map
consult-gh-embark-repos-actions-map
consult-gh-embark-general-actions-map

Is there a reason why there's no `consult-gh-embark-issues-action-map`?

**Comment by armindarvish** [comment]
@agzam Yeah there were some issues, but it should all be sorted out in develop now, check and see if it's working and let me know.

There should be an issues-actions-map as well, now.
