### ISSUE TITLE
Create new repo?

### ISSUE THREAD

**Issue by jdtsmith** [armindarvish/consult-gh#54]
**Is your feature request related to a problem? Please describe.**

I often start playing around with some code, then decide I should create a repo for it. I've not found a way to do this with forge.  

**Describe the solution you'd like**

A command that prompts for a repo name, then creates a new one in the default directory of the current buffer, then clones it locally into the default directory. 

**Describe alternatives you've considered**

Now I create one on GH, then with magit, create a repo locally, add the former as a remote, sync, and switch branches.

**Comment by jdtsmith** [comment]
Looks like a good option, thanks.  I'll look into it.

**Comment by armindarvish** [comment]
I'm closing this issue since there is no new activity. Feel free to reopen if needed.

**Comment by armindarvish** [comment]
@jdtsmith Just FYI ended up implementing this in the develop branch now because I'm trying to integrate consult-gh with some other packages like [consult-omni](https://github.com/armindarvish/consult-omni) to allow making new projects without opening terminal.
