### ISSUE TITLE
non-unicode chracter added to the end of history elements

### ISSUE THREAD

**Issue by armindarvish** [armindarvish/consult-gh#60]
Moving the discussion from https://github.com/minad/consult/issues/817 here for reference:

>I have been having this issue while working on [consult-gh](https://github.com/armindarvish/consult-gh/), where a non-unicode character is added to strings when the selection is saved in a history variable. I was hacking my code to clean this up, but now I realize that this is happening with consult-buffer-history and a bunch of other consult-something-history variables as well and here is a screenshot
Screenshot 2023-07-06 at 8 16 09 AM
I copied the character elsewhere and found out it is this character: �
I am on MacOS and I tried this in a minimal config (just consult and vertico installed) and this is still happening.
>

@minad suggested that I can use consult--read instead of consult--multi. This would simplify everything but there are challenges with that I need to figure out. I am opening this issue to track the progress on this.

**Comment by armindarvish** [comment]
with `consult--multi`, I can make sources from different repos and when I select the cnadidate, it returns the entire source including propertized text. As a result I can pass other information along with the candidate (e.g. url, owner of the repo, ...) and use it later for actions, previews, and other purposes. But with `consult-read`, I don't know how to achieve this. If I just pass a list of propertized strings, after selection the properties are not returned!

Here are some snippets to demonstrate the difference:
* using consult--multi:
```emacs-lisp
(let* ((items '(#("armindarvish/consult-gh" 0 23 (:repo "armindarvish/consult-gh" :user "armindarvish" :description "" :visible "public" :version "2023-09-03T20:18:41Z"))
                #("minad/consult" 0 13 (:repo "minad/consult" :user "minad" :description ":mag: consult.el - Consulting completing-read" :visible "public" :version "2023-09-13T09:10:12Z"))))
       (candidates (list `(:items  ,items))))
  (consult--multi candidates
                  :prompt "Select Repositories(s): "
                  :require-match t
                  :sort nil
                  :group #'consult-gh--repo-group
                  :history 'consult-gh--repos-history
                  :category 'consult-gh-repos
                  :sort t
                  :preview-key consult-gh-preview-key
                  )
  )
```
* using consult--read:
```emacs-lisp
(let* ((items '(#("armindarvish/consult-gh" 0 23 (:repo "armindarvish/consult-gh" :user "armindarvish" :description "" :visible "public" :version "2023-09-03T20:18:41Z"))
                #("minad/consult" 0 13 (:repo "minad/consult" :user "minad" :description ":mag: consult.el - Consulting completing-read" :visible "public" :version "2023-09-13T09:10:12Z")))))
  (consult--read items
                  :prompt "Select Repositories(s): "
                  :require-match t
                  :sort nil
                  :group #'consult-gh--repo-group
                  :history 'consult-gh--repos-history
                  :category 'consult-gh-repos
                  :sort t
                  :preview-key consult-gh-preview-key
                  )
  )

```

@minad, Any suggestions on how to pass other info to consult--read?

**Comment by minad** [comment]
See the :lookup argument to restore the candidate. There are a few examples in the consult source.

**Comment by armindarvish** [comment]
@minad Ok, Thanks! the :lookup argument can pass the extra info and retrieve it, but then I still don't have that information available for annotation. Does that mean that I have to manually add the annotation to each candidate string and use text-properties to get the same effect as using consult--multi?

**Comment by minad** [comment]
> Does that mean that I have to manually add the annotation to each candidate string and use text-properties to get the same effect as using consult--multi?

Yes, there are many commands in Consult which attach text properties like this.

**Comment by armindarvish** [comment]
With introducing consult-async approach (#65), I also cleaned up the rest of the repo, so this is now not an issue anymore.
