### ISSUE TITLE
Support embark export

### ISSUE THREAD

**Issue by ParetoOptimalDev** [armindarvish/consult-gh#69]
**Is your feature request related to a problem? Please describe.**

I sometimes want to go through a list of search results and having them collected/saved in a buffer would be very useful.

**Describe the solution you'd like**
M-x consult-gh-search-code mysearch RET
C-. ;; embark-act
E ;; embark-export

Hitting `RET` on a buffer would then do the same thing as hitting enter within the normal prompt from `consult-gh-search-code`.

**Describe alternatives you've considered**
Not having it.

**Additional context**

**Comment by armindarvish** [comment]
This is a combination of two different issues:

1- the embark menu for codes was missing. I added one.

2- Default actions in embark menu were running the same command that opens the minibuffer.
I created a new issue (#70) to keep track of no. 2 and already resolved it.

After merging #71 both issues are addressed. 

@ParetoOptimalDev, try it now and let me know if everything looks good! I am closing this issue now.

**Comment by ParetoOptimalDev** [comment]
You are awesome!

I will try this out tomorrow. This should make it much easier for me to replace my github code search workflow with emacs.

So long as it's not too api query intensive I should be able to very quickly preview results of files with consult preview key too!
