### ISSUE TITLE
Improve Customize Types

### ISSUE THREAD

**Issue by swflint** [armindarvish/consult-gh#73]
**Is your feature request related to a problem? Please describe.**

The type specifications in `defcustom` seem inadequate or incorrect for some customize variables.

Off the top of my head, `consult-gh-default-orgs-list` has a less-than-helpful type of `list` (using `'(repeat string)` or better `'(repeat :tag "Organizations" (string :tag "Org"))`.

**Describe the solution you'd like**
Update customization types to improve customize interface (will also improve type checking for those of us using `setopt`.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by armindarvish** [comment]
This is now done. I have submitted recipes to MELPA and am working on resolving issues so we can have the package in MELPA. closing this issue now.
