### ISSUE TITLE
Submit to MELPA

### ISSUE THREAD

**Issue by swflint** [armindarvish/consult-gh#74]
I really like this package, but I suspect that it won't find as many users as it could, as it's not available on MELPA.  I've submitted a number of packages, so I know that getting things to pass their standards can take some work.  Let me know if you'd like some help!

**Comment by adisbladis** [comment]
Submitting to MELPA simplifies things for us in nixpkgs. We automatically package elpa/melpa, but some packages are manually packaged, this being one of them.
By submitting to MELPA it will be picked up by our automation and lessen maintenance burden.
