### ISSUE TITLE
Command consult-gh-search-issues fails on any search input

### ISSUE THREAD

**Issue by dizzyyogi** [armindarvish/consult-gh#98]
**Describe the bug**
Command consult-gh-search-isssues invokes "gh search issues ..." which is not supported by latest gh version on Ubuntu (apt).
Issue search should instead use the subcommand "gh issue list --search ..."

**To Reproduce**
Invoke M-x consult-gh-search-issues from any repo.
Type any search string
Following error message appears in the echo area: 
   _unknown command "search" for "gh"_

**Expected behavior**
No error message and successful search.

**Screenshots**

**Important Information:**
 - OS: any
 - Version of Emacs
   Emacs 29.0.91
 - Version of `gh` (run `gh --version` in a shell)
   gh version 2.4.0+dfsg1 (2022-03-23 Ubuntu 2.4.0+dfsg1-2)
 - Version of `consult` (see [pkg-info](https://github.com/emacsorphanage/pkg-info))
    consult v1.0
 - The installation method and the configuration you are using with your consult-gh.
   Installed with use-package + straight
 - If there is an error message, turn debug-on-error on (by `M-x toggle-debug-on-error`) and include the backtrace content in your report.
   N/A
 - If the error only exists when you have some other packages installed, list those packages (e.g. problem happens when evil is installed)
   N/A

**Additional context**

**Comment by armindarvish** [comment]
@dizzyyogi Github CLI latest release is 2.39.2 (https://github.com/cli/cli/releases) which is a week old. 

2.4.0 must be ancient!, I am not sure why Ubuntu package manager is still stuck on 2.4.0 version.

I'd suggest you update your package manager's repository or manually upgrade gh to the latest version. The instructions below might help:

https://github.com/cli/cli/blob/trunk/docs/install_linux.md
