### ISSUE TITLE
consult-gh-repo-clone prints "[repo] was cloned to [path]" even though cloning failed

### ISSUE THREAD

**Issue by sethidden** [armindarvish/consult-gh#99]
**Describe the bug**
consult-gh-repo-clone misleadingly prints that cloning succeeded even though the *Messages* buffer prints errors and the cloned repo doesn't appear in the target dir

```
Cloning into ’/Users/rt/myrepo...
ssh_askpass: exec(/usr/X11R6/bin/ssh-askpass): No such file or directory

git@github.com: Permission denied (publickey).

fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
failed to run git: exit status 128

repo sethidden/myrepo was cloned to /Users/rt/myrepo
```

**To Reproduce**
I'm having difficulties predicting what would be the problem here. My `gh` is set to prefer SSH, and my SSH key has a passphrase, so perhaps consult-gh-repo-clone uses a dumb non-interactive terminal where its not possible to input the password? I wonder what magit does differently.

Anyway, the point here is that it seems that consult-gh-repo-clone continues despite gh clone returning a non-zero exit code, and prints the success message. I assume that my *specific* error messsage about ssh_askpass is unimportant.

**Expected behavior**
The success message should not be printed. An error message should be printed instead.

**Screenshots**
N/A

**Important Information:**
 - OS: [e.g. macOS] macOS Ventura
 - Version of Emacs [e.g. 29] (or other Emacsen you use) 30
 - Version of `gh` (run `gh --version` in a shell):
    ```
    gh version 2.39.1 (2023-11-14)
    https://github.com/cli/cli/releases/tag/v2.39.1
    ```
 - Version of `consult` (see [pkg-info](https://github.com/emacsorphanage/pkg-info)) 0.35
 - The installation method and the configuration you are using with your consult-gh.
    ```
        (use-package consult-gh
      :after embark
      :straight (consult-gh :type git :host github :repo "armindarvish/consult-gh" :after consult)
      :config
      (setq consult-gh-default-clone-directory "~/dev/"
            consult-gh-default-orgs-list '("vuestorefront" "sethidden")
    consult-gh-prioritize-local-folder t))
    ```
 - If there is an error message, turn debug-on-error on (by `M-x toggle-debug-on-error`) and include the backtrace content in your report.
   debug-on-error doesn't trigger. There's no backtrace.
 - If the error only exists when you have some other packages installed, list those packages (e.g. problem happens when evil is installed) N/A

**Additional context**
N/A

**Comment by armindarvish** [comment]
@sethidden 
The messaging is now fixed in both develop and main branch.

For cloning, consult-gh is calling `gh` and that should not require password entry. Can you run 

```
gh config list
```

in the command line and let me know what is the value for `git_protocol`?
